language: python
sudo: false
env:
  global:
    - secure: "YIEZal9EBTL+fg2YmoZoS8Bvt3eAVUOZjb38CtqpzR2CCSXWoUk35KG23m2NknlY1iKfYJyt7XWBszT/VKOQEbWQq7PIakV4vIByrWacgBxy1x3WC+rZoW7TX+JJiL+y942qIYbMoNMMB8xFpE5RDLSjSecMpFhJJXoafVTvju8="
    - secure: "R+hKWd1cyBr8eaisZsGLF9y+UUDMP9XJAmHLXzhdpS+z/ynDvgSkZPB+6CWazhUS3hGJNkjcp+aT9BGRsh9z6Co1s2GViVRv2kJh1K3sENaIRWhYxtx1PU5AHMb+UxpKae6+Gwku7erx1pa4IfJ4DVaKjoUmxYRpfD1rVHIDkfi5s7KQAfqF6DrABalGY/JVxDwfreJSKDqvE6vsjD0B7N5aOqDJIfuB76BEvKopsaVHtaXYUiykExj8eKO9qjEB3HSXf8CX0rJLqrQ0Q6YghuP8B8dO7AZ4hNnztUmqmdwJh8V4V7boh22UPvKJeXpGTOltMl2yijQXZMnPlL2vlh25lLqOgtYgCb7ti7Gh77PkyL55cGlKj20mXzaH9HHvlXfu0/8Ai1HhMD9y6I5FhVTgzGeJ3hPt8U6IVqwoanVb3e1jzOu7gL68xNNbgHzAU6uEkipwBtqoYgbYlNBg/4WEpL1T8FFCsgDKoW7awm+gmisQa+8z186y110+gxgVslqfm03+9bxIT3+/LndOwcxfucyi6Va1ESS3jSL2U7WWo2BrhNE62w7px7zHEGSOEAzxAIDOBx5qeBqNwFhr1aNdOVsfLTQyGRb0Mt2mOvaFUhyhc0cBbFSUpb1AR4QegYd8f8itcOb7eKieXR1JpXuPxYyhTFQk73RkeoDFaUQ="
dist: trusty

matrix:
  include:
    - python: 3.6
      env:
        - TEST_SPHINX="true"
        - FASTCACHE="false"
      addons:
        apt:
          packages:
            - graphviz
            - inkscape
            - texlive
            - texlive-xetex
            - texlive-fonts-recommended
            - texlive-latex-extra
            - latexmk
            - lmodern
            - librsvg2-bin
            - imagemagick
            - docbook2x

before_install:
  - if [[ "${FASTCACHE}" != "false" ]]; then
      pip install fastcache;
    fi
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
      pip install "sphinx" "docutils" requests;
      pip install git+https://github.com/ylemkimon/doctr.git@wiki;
    fi
  - |
    if [[ "${TEST_OPT_DEPENDENCY}" ]]; then
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
        if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -q -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -q -O miniconda.sh;
        fi
        bash miniconda.sh -b -p $HOME/miniconda;
        export PATH="$HOME/miniconda/bin:$PATH";
        hash -r;
        conda config --set always_yes yes --set changeps1 no;
        conda update -q conda;
        conda config --prepend channels conda-forge --prepend channels symengine/label/dev;
        conda info -a;
        conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip ${TEST_OPT_DEPENDENCY/autowrap/libgfortran libgcc gcc cython};
        source activate test-environment;
    elif [ "$TRAVIS_PYTHON_VERSION" != "pypy" ]; then
        pip list --format=legacy | grep "numpy" && pip uninstall -y numpy;
    fi
  - if [[ "${TEST_SAGE}" == "true" ]]; then
      sudo apt-add-repository -y ppa:aims/sagemath;
      sudo apt-get update;
      sudo apt-get install -y sagemath-upstream-binary;
    fi
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      pip install matchpy;
    fi
install:
  # If a command fails, fail the build.
  - set -e
  - if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ];
      then virtualenv -p /usr/bin/pypy ~/.venv;
           . ~/.venv/bin/activate;
    fi
  # -We:invalid makes invalid escape sequences error in Python 3.6. See
  # -#12028.
  - |
    if [[ "${TEST_SAGE}" != "true" ]]; then
      pip install mpmath;
      if [[ "${TEST_SETUP}" == "true" ]]; then
      # The install cycle below is to test installation on systems without setuptools.
        pip uninstall -y setuptools;
        python -We:invalid setup.py install;
        pip uninstall -y sympy;
        pip install --upgrade setuptools;
      fi
      python -We:invalid -m compileall -f sympy/;
      python -We:invalid setup.py install;
      pip list --format=columns;
    fi
script:
  # Don't run doctr if the build fails
  - set -e
  - if [[ "${TEST_SPHINX}" == "true" ]]; then
        cp bin/changelog.py ~/changelog.py;
        chmod +x ~/changelog.py;
        doctr deploy . --built-docs . --key-env CHANGELOG_DEPLOY_KEY --key-path changelog_deploy_key.enc --deploy-repo ylemkimon/sympy.wiki --no-sync --command '~/changelog.py';
    fi
  - bin/test_travis.sh
notifications:
  email: false
